# Generated by Django 5.1.7 on 2025-03-18 05:18

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            product.slug = slugify(product.name)
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_options_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
